name: CI
on:
  - "push"
  - "pull_request"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "16.x"
      - name: "Install all dependencies"
        run: "npm install"
      - name: "Check formatting"
        run: "npm run fmt:check"
      - name: "Check linting"
        run: "npm run lint:check"
      - name: "Install zx globally"
        run: "npm i -g zx"
      - name: "Set new version"
        if: "github.ref == 'refs/heads/main'"
        id: "getInc"
        run: |
          .github/scripts/newVersion << EOF
              ${{ toJSON(github.event) }}
          EOF
      - name: "Update package.json and changelog"
        if: "steps.getInc.outputs.newVersion"
        run: |
          .github/scripts/updateVersions ${{ steps.getInc.outputs.newVersion }}

          git add .

          git commit -m "chore(version): Updated package.json and moved changelog version."

          git tag "${{ steps.getInc.outputs.newVersion }}"

          git push -u origin {main,${{ steps.getInc.outputs.newVersion }}}

          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

          cat ~/.npmrc
