name: CI
on:
  - "push"
  - "pull_request"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "16.x"
      - name: "Install all dependencies"
        run: "npm install"
      - name: "Check formatting"
        run: "npm run fmt:check"
      - name: "Check linting"
        run: "npm run lint:check"
      - name: "Install zx globally"
        run: "npm i -g zx"
      - name: "Set version"
        if: "github.ref == 'refs/heads/main'"
        id: "getInc"
        run: |
          .github/scripts/newVersion << EOF
              ${{ toJSON(github.event) }}
          EOF
      - name: "Show version"
        if: "steps.getInc.outputs.newVersion"
        run: "echo ${{ steps.getInc.outputs.newVersion }}"
